name: faceit-user-store-svc

networks:
  redpanda_redpanda_network:
    external: true

services:
  faceit-user-store-svc-migrations:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      faceit-user-store-svc-db:
        condition: service_healthy
        restart: true
    command: /go/bin/goose -dir /go/src/app/internal/database/migrations postgres "host=faceit-user-store-svc-db port=5432 user=root password=root dbname=faceit-user-store-svc-db sslmode=disable" up
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=faceit-user-store-svc-db
      - DB_HOST=faceit-user-store-svc-db
      - DB_PORT=5432
    networks:
      - redpanda_redpanda_network

  faceit-user-store-svc-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'faceit-user-store-svc-db'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d faceit-user-store-svc-db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - redpanda_redpanda_network

  faceit-user-store-svc-app:
    command: air
    depends_on:
        - faceit-user-store-svc-db
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=faceit-user-store-svc-db
      - DB_HOST=faceit-user-store-svc-db
      - DB_PORT=5432
      - GRPC_SERVER_PORT=50051
      - SERVICE_NAME=user-store-svc
      - ENVRIONMENT=local
      - KAFKA_CLUSTER_URL=redpanda-0:9092
      - KAFKA_CLIENT_ID=user-store-svc
      - KAFKA_USERNAME=superuser
      - KAFKA_PASSWORD=secretpassword
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    networks:
      - redpanda_redpanda_network
    ports:
        - "50051:50051"