version: "3"

services:
  app:
      command: reflex -sr '\.go$|\.mod$' -- sh -c "go run cmd/main.go"
      build:
        dockerfile: Dockerfile.local
        context: .
      depends_on:
        - db
        - redis
      environment:
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_NAME=user-store-db
        - DB_HOST=db
        - DB_PORT=5432
        - GRPC_SERVER_PORT=50051
        - CACHE_HOST=redis
        - CACHE_PORT=6379
        - SERVICE_NAME=user-store-svc
        - ENVRIONMENT=local
      volumes:
        - .:/go/src/app
      working_dir: /go/src/app
      ports:
        - "50051:50051"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'user-store-db'
    ports:
      - "5432:5432"