name: Run - Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Run Tests
      run: |
        cd src/tests/integration
        go test -count=2 -v ./...

    - name: Generate Coverage Profile
      run: go test -coverprofile=coverage.out ./...

    - name: Display Coverage Percentage
      run: |
        coverage_percentage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        echo "Coverage percentage: $coverage_percentage"
        if (( $(echo "$coverage_percentage < 80" | bc -l) )); then
          echo "Coverage is less than 80%."
          exit 1
        fi